//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITDB.Model.Main_AdoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_company_details
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string company_name { get; set; }
        public Nullable<int> company_logo_Id { get; set; }
        public string company_web_link { get; set; }
        public string system_comment { get; set; }
        public System.DateTime added_date { get; set; }
        public System.DateTime updated_date { get; set; }
        public string added_by { get; set; }
        public string updated_by { get; set; }
        public bool is_active { get; set; }
        public int trust_id { get; set; }
        public string contact_number { get; set; }
    }
}
