//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITDB.Model.Main_AdoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_category
    {
        public int id { get; set; }
        public string category { get; set; }
        public string system_comment { get; set; }
        public System.DateTime added_date { get; set; }
        public System.DateTime update_date { get; set; }
        public string added_by { get; set; }
        public string update_by { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
