//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITDB.Model.Main_AdoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_globle_note
    {
        public long id { get; set; }
        public long related_id { get; set; }
        public long document_id { get; set; }
        public int section_id { get; set; }
        public string system_comment { get; set; }
        public System.DateTime added_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string added_by { get; set; }
        public string updated_by { get; set; }
        public bool is_Active { get; set; }
    }
}
