//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITDB.Model.Main_AdoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tag
    {
        public long TagId { get; set; }
        public string TagName { get; set; }
        public System.DateTime added_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string added_by { get; set; }
        public string updated_by { get; set; }
        public bool is_active { get; set; }
    }
}
